<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Practica6" nsURI="Practica6" nsPrefix="Practica6">
  <eClassifiers xsi:type="ecore:EClass" name="Esquema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablas" upperBound="-1"
        eType="#//Tabla" containment="true" eOpposite="#//Tabla/esquema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tabla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnas" upperBound="-1"
        eType="#//Columna" containment="true" eOpposite="#//Columna/tabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fks" upperBound="-1" eType="#//FK"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="esquema" lowerBound="1"
        eType="#//Esquema" eOpposite="#//Esquema/tablas"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Columna">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esPK" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permiteNulos" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabla" lowerBound="1" eType="#//Tabla"
        eOpposite="#//Tabla/columnas"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FK">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencia" lowerBound="1"
        eType="#//Tabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columna" lowerBound="1"
        eType="#//Columna"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDato">
    <eLiterals name="Entero"/>
    <eLiterals name="Real" value="1"/>
    <eLiterals name="Caracter" value="2"/>
    <eLiterals name="Cadena" value="3"/>
    <eLiterals name="Boolean" value="4"/>
    <eLiterals name="Fecha" value="5"/>
    <eLiterals name="FechaHora" value="6"/>
  </eClassifiers>
</ecore:EPackage>
